App:
  Name: irisProject
  LimitPerMin: 20
Postgres:
  host: localhost
  port: 5432
  user: iris
  password: password
  database: iris
JWT:
  ExpireHours:
    8
  PrivateBytes: |
    -----BEGIN EC PRIVATE KEY-----
    MIHcAgEBBEIA6sUEHwkFkR98BgNlp/jaavxgv0i/zqireTf/OtOwoJ0TDP4CQhaD
    L4jIgcKhqVNxVem645F3Nd6OxJ+23v7Om3OgBwYFK4EEACOhgYkDgYYABAFZaH2c
    ithk3Awr/6Yke+NKXex9ne+se136B301p/G5sBJ9+s6dyXXFK3BxLRmEwlHNyHgx
    u2pzb3SP3XgKwGSUigEhZBN1gLoEQx9yqD2HGxQf1StPAPzFfAnrrhlaXvQFvblo
    4222hb2yG8WdHxvzU9colsHuakxP5X9Zo8qHFgQ7Qg==
    -----END EC PRIVATE KEY-----
  PublicBytes: |
    -----BEGIN PUBLIC KEY-----
    MIGbMBAGByqGSM49AgEGBSuBBAAjA4GGAAQBWWh9nIrYZNwMK/+mJHvjSl3sfZ3v
    rHtd+gd9NafxubASffrOncl1xStwcS0ZhMJRzch4Mbtqc290j914CsBklIoBIWQT
    dYC6BEMfcqg9hxsUH9UrTwD8xXwJ664ZWl70Bb25aONttoW9shvFnR8b81PXKJbB
    7mpMT+V/WaPKhxYEO0I=
    -----END PUBLIC KEY-----
File:
  SaveDir: /User/chenbai/Temp/


